import 'avalanche-css'
import './src/assets/scss/_reset.scss'
import './src/assets/scss/_vars.scss'
import './src/assets/scss/_layout.scss'
import './src/assets/scss/_fonts.scss'
import './src/assets/scss/_btns.scss'
import './src/assets/scss/_header.scss'
import './src/assets/scss/_footer.scss'
import './src/assets/scss/components/_slider.scss'
import './src/assets/scss/components/_bk-news.scss'
import './src/assets/scss/components/_bk-card.scss'
import './src/assets/scss/components/_bk-timeline.scss'

import './src/assets/js/components/header.js'
import './src/assets/js/components/card.js'
import './src/assets/js/components/timeline.js'
import './src/assets/js/components/news.js'
import './src/assets/js/components/slider.js'
