name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou le nom de votre branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Generate static files
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "./dist"
          publish_dir: .output/public
          publish_branch: github-pages # Spécifie la branche de déploiement
          force_orphan: true # Crée une nouvelle branche sans historique
